apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: v56-openagentic
servers: 1
agents: 2
volumes:
  - volume: /mnt/e/development/openagentic-sdk:/var/lib/openagentic/repo
    nodeFilters:
      - all
