apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: v56-openagentic
servers: 1
agents: 2
ports:
  - port: 16686:16686
    nodeFilters:
      - loadbalancer
volumes:
  - volume: __OA_REPO_ROOT__:/var/lib/openagentic/repo
    nodeFilters:
      - all
